# Note that the following stanza uses CircleCI 2.1 to make use of a Reusable Executor
# This allows defining a docker image to reuse across jobs.
# visit https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-executors to learn more.

version: 2.1
orbs:
  portshiftscanner: 'portshift-scanner/portshift@dev:0.0.1'
jobs:
  docker-build:
    machine: true
    steps:
      - checkout
      - run: 'docker pull mongo:latest'
workflows:
  scan-image:
    jobs:
      - docker-build
      - portshiftscanner/scan-image:
          requires:
            - docker-build
          image_name: 'mongo'
          image_tag: 'latest'
          access_key: '29557d7f-b2d5-4304-934b-872033244a83'
          secret_key: '9S/b+FJ0lWrHIpt5OlQ7I8kg1pYT9YuQ1JYNrFNkC54='
          portshift_server: 'tomer5.demo.portshift.co'
