# Note that the following stanza uses CircleCI 2.1 to make use of a Reusable Executor
# This allows defining a docker image to reuse across jobs.
# visit https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-executors to learn more.

version: 2.1
orbs:
  portshiftscanner: 'portshift/portshift-scanner@2.0.1'
jobs:
  install:
    portshift_server: 'tomer5.demo.portshift.co'
workflows:
  scan-image:
    jobs:
      - portshiftscanner/scan-image:
          context: context
          image_name: 'mongo'
          image_tag: 'latest'
          portshift_server: 'tomer5.demo.portshift.co'
